### ISSUE TITLE
sort by channel names?

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-hcp#17]
@dengemann is there any specific reason that the `sort_by_ch_names` param is set to `False` here: https://github.com/mne-tools/mne-hcp/blob/master/hcp/io/read.py#L96 ?

It is making it hard to look for channels in the epochs plotter ...

**Comment by dengemann** [comment]
Same as before Mainak, the channels must not be sorted to be compatible
with native layout. In BTI the names don't correspond to the order.

**Comment by jasmainak** [comment]
okay. But I do I run into any danger if I use `read_raw_bti` from MNE with `sort_by_ch_names=True` ? I'm not doing any source localization

**Comment by dengemann** [comment]
> But I do I run into any danger if I use read_raw_bti from MNE with sort_by_ch_names=True ? 

It will break at a certain point because the ordering in the mat files of the HCP cannot be really determined due to missing channels (BADS), we need to rely on the original sorting. In other words if you change it at the mne-hcp level you will construct inconsistent channel lists ...

> It is making it hard to look for channels in the epochs plotter ...

Can't we do some high-level fix here? ... e.g. rename channels? The thing is that the nativer order follows a clear spatial logic ... just that it is not expressed in an obvious way.

**Comment by jasmainak** [comment]
> It will break at a certain point because the ordering in the mat files of the HCP cannot be really determined due to missing channels (bads)

I'm not sure which mat files you are talking of, but for ICA I think we can pick the right channels ...

anyway, your high-level fix of renaming channels sounds reasonable enough for me. So I'll close the issue. Thanks @dengemann !

**Comment by dengemann** [comment]
> I'm not sure which mat files you are talking of,

precisely, we cannot easily construct a valid channel info from the epochs or evoked files. For interpolation you need the full info. So we read that from the raw files. Here keeping channel orders native turned out to alleviate pain. But keep in mind that the channels have a meaningful order. You can in principle rename them from MEG 1-248. See the native layout and it's snake pattern with A1 at the midpoint:

![bti_layout](https://cloud.githubusercontent.com/assets/1908618/17647738/0d18bc98-61ff-11e6-98e8-cdd7431bca79.png)
